const express = require('express')
const Addinvoics = require("../controler/invoices/Addinvoics")
const Getallinvoices = require('../controler/invoices/Getallinvoices')
const updateInvoices = require('../controler/invoices/updateInvoices')
const DeleteInvoices = require('../controler/invoices/DeleteInvoices')
const GetspasficInvoies = require("../controler/invoices/GetspasficInvoies")
const router = express.Router()
router.post("/add-invoices" , Addinvoics )
router.get('/' , Getallinvoices)
router.route('/:id').put(updateInvoices).delete(DeleteInvoices).get(GetspasficInvoies)
module.exports = router