const express = require('express')
const router  = express.Router()
const Addmission  = require('../controler/missions/Addmission')
const Getallmission = require('../controler/missions/Getallmission')
const updateMission = require('../controler/missions/updateMission')
const DeleteMission = require("../controler/missions/DeleteMission")
const Getpasifcreport = require('../controler/missions/Getspasifcreport')
const userMission = require('../controler/missions/userMission')
const autentcatuserLogin = require('../miidelware/authentcateuser')
router.post('/new-mission' ,autentcatuserLogin ,  Addmission)
router.route('/').get(autentcatuserLogin , Getallmission)
router.get('/user' ,autentcatuserLogin ,userMission)
router.route('/:id').put(autentcatuserLogin , updateMission).delete(autentcatuserLogin , DeleteMission).get(autentcatuserLogin , Getpasifcreport)
module.exports = router